### ISSUE TITLE
Expose more controls to the user 

### ISSUE THREAD

**Issue by jsiegle** [AllenNeuralDynamics/parallax#17]
Currently, a number of important functions (such as camera focusing and stage translation) require modifier keys and/or middle mouse button scrolls/clicks. It's fine to keep these shortcuts, but there should also be buttons or drop-down menus that can be used instead.

**Comment by chronopoulos** [comment]
update: stage translation is now controllable via the Targeting Dialog (crosshairs button). camera focusing relies on ctrl+shift+scroll wheel - i will implement a dialog window to control this from the screen.

i believe all other keyboard shortcuts have buttons analogs, but let me know if i'm missing anything
