### ISSUE TITLE
Integrate Zaber motor control into the GUI

### ISSUE THREAD

**Issue by jsiegle** [AllenNeuralDynamics/parallax#3]
At a minimum, we need the following controls:

- [x] Real-time position display (can just be a number, but ideally this would show a diagram with the full range, set points, and current location)
- [x] Ability to store and load set points. Most importantly, we'll need the "experiment" position and the "insert/remove mouse" position, but there may be other points we want to save as well (e.g. for removing probes).

**Comment by jsiegle** [comment]
The motor control interface should live in a separate window that's only visible when needed, to prevent accidental clicks. It would be great if it could display a warning if the user requests a move when stages are not fully retracted.

We should also measure the repeatability of the motor positioning -- if it's sufficiently precise (~10 microns), then it may not be necessary to re-calibrate the stage offset when the Zaber motor moves to the "experiment" position.

**Comment by chronopoulos** [comment]
update: zaber control has been implemented as a separate window (Tools > Elevator Control), and real-time coordinates are polled from the devices. the interface allows you to control the setpoints, both in firmware as well as software setpoints.

i'll leave this open until the "warning if not retracted" feature is implemented.
